examples/noso-go-run.sh
Hi Levi,
Adding an example of a Linux shell script.
I've included all the know pools up till now, from the NosoMiner's poolist.txt
Cheers,
Gus
=> Add linux shell script

Makefile
=> Include shell script with linux/macos packages

cmd/mine.go, internal/miner/parse.go, internal/miner/payments.go
- Closes #21 
- Update parsing of PAYMENTOK response from pool
- Include pool balance at time of payment request with what is written
to payments.csv
=> 21 Update PAYMENTOK parsing and payments.csv writing

internal/miner/payments.go
- Fixes 21
- Fixes double period in payment amount
- Fixes wallet address payment is made to
=> Fix PAYMENTOK parsing errors

examples/noso-go-run.sh
Hey Levi,
Is this good?
Cheers,
Gus
=> chore: Add RussiaPool

cmd/mine.go
=> Include app info in initial CLI output

internal/miner/client.go, internal/miner/comms.go, internal/miner/mine.go, internal/miner/parse.go
- If we get a PASSFAILED from pool, close current client and create a
new one
=> Close current TCP client and restart

internal/miner/client.go, internal/miner/comms.go, internal/miner/mine.go, internal/miner/parse.go
=> Revert "Close current TCP client and restart"

cmd/pool.go, examples/noso-go.bat, examples/noso-go.sh
- Add mining.moe to `pool` command
- Remove dead pools nosodev, hodl, nosopoolde
=> Updates to known pools

.github/workflows/main.yaml, Makefile, cmd/mine.go, cmd/pool.go, internal/miner/client.go, internal/miner/comms.go, internal/miner/jobs.go, internal/miner/mine.go, internal/miner/miner.go, internal/miner/opts.go, internal/miner/parse.go, internal/miner/payments.go, internal/miner/solution.go, internal/miner/version.go
Closes #34 
Closes #45 
Closes #54
Closes #55 
Closes #57 
Closes #58 
Closes #61 
Implements new Proof of Participation protocol.
=> Implement new Proof of Participation protocol

Makefile, README.md, cmd/mine.go, cmd/pool.go, cmd/root.go, go.mod, internal/miner/mine.go, main.go
=> [70] Replace references to `leviable` with `Noso-Project`

cmd/pool.go, cmd/status.go, internal/miner/client.go, internal/miner/comms.go, internal/miner/mine.go, internal/miner/parse.go, internal/miner/status.go
=> Add status command to noso-go CLI

internal/miner/mine.go, internal/miner/payments.go, internal/miner/utils.go, internal/miner/utils_test.go
=> Move poolBalance and parseAmount to utils and add tests

.gitignore, internal/miner/client.go, internal/miner/mine.go, internal/miner/parse.go, internal/miner/payments.go, internal/miner/solution.go, internal/miner/status.go
=> [86] Switch to `log` package for printing output

cmd/pool.go
=> [93] Add YZpool back to known pools

cmd/pool.go
=> [95] Update devnoso pool DNS

internal/miner/client.go
=> [101] Add miner wallet address to PING message

internal/miner/mine.go
=> [100] Show miner's wallet address in 60s status output

cmd/mine.go, cmd/pool.go, internal/miner/mine.go, internal/miner/opts.go
=> [89] Make mining status interval configurable

internal/miner/client.go, internal/miner/comms.go, internal/miner/jobs.go
=> [66] Dont hash when disconnected from pool

internal/miner/client.go
Reverts Noso-Project/noso-go#102
After speaking to main Noso dev, this is not needed.
=> Revert "[101] Add miner wallet address to PING message"

cmd/mine.go, cmd/pool.go, examples/noso-go-multi-addresses.sh, internal/miner/client.go, internal/miner/mine.go, internal/miner/opts.go, internal/miner/solution.go
=> [108] Add --exit-on-retry flag

cmd/pool.go, examples/noso-go.bat, examples/noso-go.sh
=> [104] Update known pool list

cmd/pool.go, cmd/status.go
=> [115] Abstract pools and pool aliases

internal/miner/client.go
=> [118] Set pool auth if empty

README.md, docs/quickstart-android.md, docs/quickstart-linux.md, docs/quickstart-macos.md, docs/quickstart-raspberrypi.md, docs/quickstart-windows.md, examples/noso-go.sh, internal/miner/mine.go
=> Update README and separate out quickstart guides

examples/noso-go.bat, examples/noso-go.sh
=> [126] Use --exit-on-retry in scripts

internal/miner/parse.go
- Closes #123
- Uses PONG responses to keep pool hash rate up to date
=> [123] Keep pool hash rate up to date

cmd/pool.go
=> [132] Re-add dukedog.io pool to known pool list
